// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jzpwstqwsmkwdpqahcpx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6cHdzdHF3c21rd2RwcWFoY3B4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1MzYxMzYsImV4cCI6MjA3MzExMjEzNn0.mg-Lz5jb5ERJBnfSUkuMLaISO8erGdho7jENxkBp6FU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});